# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
jQuery.ajaxSetup async: false

@newTorrent = (url) ->
  resp = $.post '/api/new_torrent', torrent: url
  console.log resp.responseText
  code = jQuery.parseJSON(resp.responseText)
  if code.success is 0
    $('.success').show().delay(5000).fadeOut()
  else
    $('.fail').show().delay(5000).fadeOut()
  return false

# ---
# generated by js2coffee 2.2.0